spring.cloud.stream:
  function:
    definition: domainProcessor
  bindings:
    domainProcessor-in-0:
      destination: web-domains
    domainProcessor-out-0:
      destination: active.web-domains
  kafka:
    streams:
      binder:
        deserializationExceptionHandler: logAndContinue
        configuration:
          spring.json.trusted.packages: '*'
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9092
